services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: chromadb/chroma
    container_name: "llm-db"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - 8000:8000
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "llm-backend"
    environment:
      - DB_HOST=db
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - 9000:9000
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "llm-frontend"
    ports:
      - 80:80
    networks:
      - default
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    driver: bridge

volumes:
  chroma-data:
    driver: local
  ollama: